name: PR Preview to gh-pages

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  deploy-preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable Corepack and Set Yarn Version
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build project
        run: yarn build
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          VITE_PREVIEW_ID: pr-${{ github.event.pull_request.number }}

      - name: Debug base and index.html
        run: |
          echo "VITE_PREVIEW_ID=$VITE_PREVIEW_ID"
          head -20 dist/index.html
        env:
          VITE_PREVIEW_ID: pr-${{ github.event.pull_request.number }}

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy build to preview folder
        run: |
          rm -rf gh-pages/preview/pr-${{ github.event.pull_request.number }}
          mkdir -p gh-pages/preview/pr-${{ github.event.pull_request.number }}
          cp -r dist/* gh-pages/preview/pr-${{ github.event.pull_request.number }}/

      - name: Commit and push preview
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add preview/pr-${{ github.event.pull_request.number }}
          git commit -m "PR #${{ github.event.pull_request.number }} preview deploy" || echo "No changes to commit"
          git push origin gh-pages

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request.number;
            const repo = context.repo.repo;
            const owner = context.repo.owner;
            const url = `https://${owner}.github.io/${repo}/preview/pr-${pr}/`;
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: pr,
              body: `🚀 Preview deployment is ready!\n\nVisit: ${url}`
            });

  cleanup-preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0

      - name: Remove preview folder
        run: |
          rm -rf preview/pr-${{ github.event.pull_request.number }}

      - name: Commit and push removal
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Remove preview for PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"
          git push origin gh-pages 
